language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script: 'true'
deploy:
  provider: heroku
  api_key:
    secure: JJNU3rxS79ndUwTo45hIUpg9m0uT92jV2fxG5d2YVxhBxd3gg0tUAMjTQT+Uoia1S0QdmBRBOPKkQ8sgnaVuf0s2bPA0FiECigcYcqpiauB+Bsqke/HepVlWfgoSA2jz3yp0zWLG0BvoMx7y0YrTwVfSLB9iAnNbGjy7O81jEJUGPCa3eyB7BrGH1h92/EvCIbGATMcqPgj5zkFnMQhtae7uc7/LLWGmRb02N9keEU267KLw7L7g5HZd+68nAr5/XTm9whjeIdbwPqRlqMTQdnQ/vKRH6ar178acy2gcxbPMApdnARVAtEfuB2+mRmQ9scnJraGMy+myeB1HdcZuMtokHO3tiBWnFSRRNUrrGX3tRjgdJxEZ2xNx2FSWTZRhsLcb2B1fw0klUvEjm63GxrKWJyfFTzX2GdE0dGmOrhZVQyarASx0+KfkKp6R0S2WnsT/lErsUBXuWwr/6+63BRjPUj4PYQaLtR4HCaVPFYjNbW2d7IShINjriNLB3AqsaL2gF0jb9074pJ7wkyi+TRlCAHoPuvydcanEONF742wEtZLmTkJh8si6h6fizBIsj/Urd7A8iWJezFTtySNw4ZpH5Q9JNKfBpU2TDo2mBloD9jiIkvPdmG6ohWQHUCXapAOOEfrEQpgVONLI+a47m1gSQSZ33fNiFw8jQukZpto=
  app: server-exercise-tracker
  on:
    repo: gabogarciam/exercise-tracker-api
