language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script: 'true'
deploy:
  provider: heroku
  api_key:
    secure: "qAOResWGQvvFKRIJ3mqZpc5WaGuTlSZWrFcEPLWg8Y7C8V9O7ywTVzQJIWdha4o0DoIUfqyPLxed0VD4t/dSLMonHe5+Oz2k5w2jScX9FPdaTOHBB1Pp3aUxqbamfObnjDbklP7oIFcvlHb1uZnCK4sdYJ8hY0qmlex+m/Z4ZUbGPcDXiH39mzhnc27ToXFJ5TUCTw0bseakEe0inhsOKrPzjC3jjiAMZ5g04juOANVsPRh2fNq4qt5xEkx+akMJRvCiOUUOf1MobdW2SlZi1NKl+CYepMob5Qqb5pCfzmzfTqPLVq4u5F6pX3zearjqL56EUeK7VxZCAL1ZOttkDmP1GJp4im0xuZN7RMCN9n2qyFz6SlVlIg9Jo5V41d/pjjYlhc4pWZEhYdW755TNZpXllsR+0qYT2B7tQpqZ+a1Ro/HZpwYM8dvRUzitShVEWetX7b6we3ircILQVHWzGvlSnLpZByh2x4/79qcRwZf82rUb7YPLh2zFPz6Y6F+/zktZw5wmC15V04mhvV6CQawzlnTL9xn8WkxCUZ+uvv7H/OUhIrP0Y+JZxatYHP9rUbGHWWl6Lqqk0SyStCHaW7gQlvKFc5rnvB1mjTE7JT9U6R5CHDh5QWuVb7fWVgeOuppdumj/p5O0EghQe8af8NS5xYqkAPpAGHxQOKRbwxM="
  app: server-exercise-tracker
  on:
    repo: gabogarciam/exercise-tracker-api