language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script: 'true'
deploy:
  provider: heroku
  api_key:
    secure: 298500f1-6b00-4569-b350-20e7c704b84b?requestor=SFMyNTY.g3QAAAACZAAEZGF0YW0AAAAMODEuMTg0LjQxLjUyZAAGc2lnbmVkbgYAZZFQ-3QB.AyLTd1N0iFqBvvdqCooHgyy2S05LWBTgBZGaxKATO9Q
  app: server-exercise-tracker
  on:
    repo: gabogarciam/exercise-tracker-api
