language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: MryRro8LP56hx6tSMYe0MhRJmdVGYcthnxNbS0IyDpC1f3bkEM3RDejBq7hZ6DFlZ5jz+1BEfa1uP8tJqVBbWMv0ODFO4+pviYYi/zY9/fX1K7WWHfrxHfgCAGm7faAcp1/Ki7QhH6qfZJP3VaCHtstaNMTmEGYaX6Fkaq8MVFMjS/XT7DVP3pYN2QIq7/UxpaZPFgQLu9y02p7B20OGc+1/IJ/QrnWi8nhA8yuXQSTC+2DFBpLY8LmNTf+yZrARYm1YjXliUG0CQbC7pwg2PjeZ88BjVjWKam/veFy83r1otBp3nMU+lZrTgSEYMLWoVWk4ylg1XKUZXHO1NsIffIoK7cuUTJjHKS8WBUhe1xOfbuwp4iKMo5V5IpEVCOrAaihy/Icvgub2R+zuhmPWI6eye4JI2GTzR4QB50ty1Kmw5ARQgXI+gaFygeoxQ8u1ArmrWy7Il+Fhbimz/5/FNS90WAWpyAeQPwOIc7L3w8NRp/jHkN4WxsD9Hds+bSuaiavCZhUUXcEsXsNbZpRR2xBpDCsDJe4DV/4COgj5iViGAJmXJN+mi7l1xckZzAVmRrs6oMWSmOHFY04gK4WWJBAmu7CVwXlp0cf1j4IeBO15hAalqeuXVMuIZZuxoqdTe7pDyfSdzQ9kxwwfUbLKJGRyvlxcph1FwujWoeoaYnE=
  app: server-exercise-tracker
  on:
    repo: gabogarciam/exercise-tracker-api
